version: "3.8"
networks:
  niyo-task:
    driver: bridge
services:
  web:
    build:
      context: .
      dockerfile: ./deployment/docker/Dockerfile.dev
    env_file:
      - deployment/docker/.env.development
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    networks:
      - niyo-task
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: niyo_task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - niyo-task
    restart: unless-stopped

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - niyo-task
    restart: unless-stopped

